#! /usr/bin/env python3

# Daemon BSD Source Code
# Copyright (c) 2024, Daemon Developers
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#  * Neither the name of the <organization> nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import datetime
import os
import subprocess
import sys
import time

if not 'script_dir_name' in globals():
	script_dir_name = os.path.dirname(os.path.realpath(__file__))

if len(sys.argv) == 1:
	repository_dir = script_dir_name
elif len(sys.argv) == 2:
	repository_dir = sys.argv[1]
else:
	raise(ValueError, "too much arguments")

if not os.path.isdir(repository_dir):
	raise(ValueError, "not a directory")

git_command_list = ["git", "-C", repository_dir]

tag_string="0"
date_string=""
ref_string=""
dirt_string=""

def runGitCommand(command_list):
	command_list = git_command_list + command_list
	return subprocess.run(command_list, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout.decode("utf-8").rstrip()

def testGitCommand(command_list):
	command_list = git_command_list + command_list
	return subprocess.Popen(command_list, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode

def getDate(timestamp):
	return datetime.datetime.utcfromtimestamp(timestamp).strftime('%Y%m%d-%H%M%S')

git_last_commit_short = runGitCommand(["rev-parse", "--short", "HEAD"])

if git_last_commit_short:
	git_describe_string = runGitCommand(["describe", "--tags", "--match", "v[0-9].*"])[1:]

	git_last_commit_timestamp = int(runGitCommand(["log", "-1", "--pretty=format:%ct"]))
	git_last_commit_date = getDate(git_last_commit_timestamp)

	git_closest_tag = runGitCommand(["describe", "--tags", "--abbrev=0", "--match", "v[0-9].*"])[1:]

	if git_closest_tag:
		tag_string = git_closest_tag

		if git_closest_tag != git_describe_string:
			date_string = "-" + git_last_commit_date
			ref_string = "-" + git_last_commit_short
	else:
		date_string = "-" + git_last_commit_date
		ref_string = "-" + git_last_commit_short
else:
	date_string = "-" + getDate(time.time())
	ref_string = "-0"

if testGitCommand(["diff", "--quiet"]) != 0:
	dirt_string = '+dirty'

print(tag_string + date_string + ref_string + dirt_string)
