set(FT_DISABLE_BROTLI ON CACHE STRING "Disable Brotli" FORCE)
set(FT_DISABLE_BZIP2 ON CACHE STRING "Disable bzip2" FORCE)
set(FT_DISABLE_HARFBUZZ ON CACHE STRING "Disable HarfBuzz" FORCE)
set(FT_DISABLE_PNG ON CACHE STRING "Disable PNG" FORCE)

if (NACL)
	set(FREETYPE_INTERNAL_ZLIB ON)
else()
	set(FREETYPE_INTERNAL_ZLIB OFF)
endif()

set(FT_DISABLE_ZLIB ${FREETYPE_INTERNAL_ZLIB} CACHE STRING "Disable external zlib" FORCE)

set(FREETYPE_DIR ${DAEMON_DIR}/libs/freetype)
set(FREETYPE_INCLUDE_DIRS ${FREETYPE_DIR}/include)

add_subdirectory(${FREETYPE_DIR})
set(FREETYPE_LIBRARIES freetype)
