// Auto-generated by VulkanShaderParser, do not modify

struct BufferCfg {
	uint  id;
	float relativeSize;
	uint  size;
	uint  usage;
};

BufferCfg bufferConfigs[5] = BufferCfg[5] (
	BufferCfg( 0, 0.0f, 566, 3 ), // buf1
	BufferCfg( 1, 0.0f, 5667, 30 ), // buf2
	BufferCfg( 2, 0.0f, 5664545, 0 ), // buf3
	BufferCfg( 3, 0.0f, 5664545, 0 ), // buf4
	BufferCfg( 4, 0.0f, 5664545, 0 ) // buf5
);

const uint bufferCount = 5;

struct SPIRVBufferCfg {
	uint id;
	uint count;
	uint buffers[16];
};

SPIRVBufferCfg SPIRVBufferConfigs[5] = SPIRVBufferCfg[5] (
	SPIRVBufferCfg( 0, 3, uint[16] ( 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ) ),
	SPIRVBufferCfg( 1, 0, uint[16] ( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ) ),
	SPIRVBufferCfg( 2, 0, uint[16] ( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ) ),
	SPIRVBufferCfg( 3, 0, uint[16] ( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ) ),
	SPIRVBufferCfg( 4, 0, uint[16] ( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ) )
);

const uint SPIRVCount = 5;