set(MATHLIST
    ${ENGINE_DIR}/renderer-vulkan/Math/Bit.h
    ${ENGINE_DIR}/renderer-vulkan/Math/NumberTypes.h
)

set(MEMORYLIST
    ${ENGINE_DIR}/renderer-vulkan/Memory/Allocator.cpp
    ${ENGINE_DIR}/renderer-vulkan/Memory/Allocator.h
    ${ENGINE_DIR}/renderer-vulkan/Memory/Array.h
    ${ENGINE_DIR}/renderer-vulkan/Memory/DynamicArray.h
    ${ENGINE_DIR}/renderer-vulkan/Memory/Memory.cpp
    ${ENGINE_DIR}/renderer-vulkan/Memory/Memory.h
    ${ENGINE_DIR}/renderer-vulkan/Memory/MemoryChunk.h
    ${ENGINE_DIR}/renderer-vulkan/Memory/MemoryChunkSystem.cpp
    ${ENGINE_DIR}/renderer-vulkan/Memory/MemoryChunkSystem.h
    ${ENGINE_DIR}/renderer-vulkan/Memory/IteratorSeq.h
    ${ENGINE_DIR}/renderer-vulkan/Memory/StackAllocator.cpp
    ${ENGINE_DIR}/renderer-vulkan/Memory/StackAllocator.h
    ${ENGINE_DIR}/renderer-vulkan/Memory/SysAllocator.cpp
    ${ENGINE_DIR}/renderer-vulkan/Memory/SysAllocator.h
    ${ENGINE_DIR}/renderer-vulkan/Memory/RingBuffer.h
)

set(SYNCLIST
    ${ENGINE_DIR}/renderer-vulkan/Sync/AccessLock.cpp
    ${ENGINE_DIR}/renderer-vulkan/Sync/AccessLock.h
    ${ENGINE_DIR}/renderer-vulkan/Sync/AlignedAtomic.h
    ${ENGINE_DIR}/renderer-vulkan/Sync/Fence.cpp
    ${ENGINE_DIR}/renderer-vulkan/Sync/Fence.h
    ${ENGINE_DIR}/renderer-vulkan/Sync/SyncPoint.cpp
    ${ENGINE_DIR}/renderer-vulkan/Sync/SyncPoint.h
)

set(SYSLIST
    ${ENGINE_DIR}/renderer-vulkan/Sys/CPUInfo.cpp
    ${ENGINE_DIR}/renderer-vulkan/Sys/CPUInfo.h
    ${ENGINE_DIR}/renderer-vulkan/Sys/MemoryInfo.cpp
    ${ENGINE_DIR}/renderer-vulkan/Sys/MemoryInfo.h
)

set(THREADLIST
    ${ENGINE_DIR}/renderer-vulkan/Thread/GlobalMemory.cpp
    ${ENGINE_DIR}/renderer-vulkan/Thread/GlobalMemory.h
    ${ENGINE_DIR}/renderer-vulkan/Thread/SyncTask.cpp
    ${ENGINE_DIR}/renderer-vulkan/Thread/SyncTask.h
    ${ENGINE_DIR}/renderer-vulkan/Thread/Task.cpp
    ${ENGINE_DIR}/renderer-vulkan/Thread/Task.h
    ${ENGINE_DIR}/renderer-vulkan/Thread/TaskData.cpp
    ${ENGINE_DIR}/renderer-vulkan/Thread/TaskData.h
    ${ENGINE_DIR}/renderer-vulkan/Thread/TaskList.cpp
    ${ENGINE_DIR}/renderer-vulkan/Thread/TaskList.h
    ${ENGINE_DIR}/renderer-vulkan/Thread/TLMAllocator.cpp
    ${ENGINE_DIR}/renderer-vulkan/Thread/TLMAllocator.h
    ${ENGINE_DIR}/renderer-vulkan/Thread/Thread.cpp
    ${ENGINE_DIR}/renderer-vulkan/Thread/Thread.h
    ${ENGINE_DIR}/renderer-vulkan/Thread/ThreadCommand.cpp
    ${ENGINE_DIR}/renderer-vulkan/Thread/ThreadCommand.h
    ${ENGINE_DIR}/renderer-vulkan/Thread/ThreadMemory.cpp
    ${ENGINE_DIR}/renderer-vulkan/Thread/ThreadMemory.h
    ${ENGINE_DIR}/renderer-vulkan/Thread/ThreadUplink.cpp
    ${ENGINE_DIR}/renderer-vulkan/Thread/ThreadUplink.h
)

set(UTILSLIST
    ${ENGINE_DIR}/renderer-vulkan/SrcDebug/LogExtend.h
    ${ENGINE_DIR}/renderer-vulkan/SrcDebug/Tag.cpp
    ${ENGINE_DIR}/renderer-vulkan/SrcDebug/Tag.h
)

# Graphics engine

set(GRAPHICSCORELIST
    ${ENGINE_DIR}/renderer-vulkan/GraphicsCore/CapabilityPack.cpp
    ${ENGINE_DIR}/renderer-vulkan/GraphicsCore/CapabilityPack.h
    ${ENGINE_DIR}/renderer-vulkan/GraphicsCore/GraphicsCoreCVars.cpp
    ${ENGINE_DIR}/renderer-vulkan/GraphicsCore/GraphicsCoreCVars.h
    ${ENGINE_DIR}/renderer-vulkan/GraphicsCore/Init.cpp
    ${ENGINE_DIR}/renderer-vulkan/GraphicsCore/Init.h
    ${ENGINE_DIR}/renderer-vulkan/GraphicsCore/Instance.cpp
    ${ENGINE_DIR}/renderer-vulkan/GraphicsCore/Instance.h
    ${ENGINE_DIR}/renderer-vulkan/GraphicsCore/Vulkan.h
)

set(VULKANLOADERLIST
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/Vulkan.cpp
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/VulkanLoader.cpp
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/VulkanLoader.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/VulkanLoadFunctions.cpp
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/VulkanLoadFunctions.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_core.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_xlib.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_xlib_xrandr.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_wayland.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_win32.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_xcb.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_vi.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_screen.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_macos.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_metal.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_ohos.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_ios.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_ggp.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_fuchsia.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vk_icd.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vk_layer.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vk_platform.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_android.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_beta.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vulkan_directfb.h
    ${ENGINE_DIR}/renderer-vulkan/VulkanLoader/vk_enum_string_helper.h
)

set(GRAPHICSLIST
    ${GRAPHICSCORELIST}
    ${VULKANLOADERLIST}
)

set(RENDERERLIST
    ${MATHLIST}
    ${MEMORYLIST}
    ${SYNCLIST}
    ${SYSLIST}
    ${THREADLIST}
    ${UTILSLIST}
    ${GRAPHICSLIST}
    ${ENGINE_DIR}/renderer-vulkan/Surface/Surface.cpp
    ${ENGINE_DIR}/renderer-vulkan/Surface/Surface.h
    ${ENGINE_DIR}/renderer-vulkan/Error.cpp
    ${ENGINE_DIR}/renderer-vulkan/Error.h
    ${ENGINE_DIR}/renderer-vulkan/Init.cpp
    ${ENGINE_DIR}/renderer-vulkan/Init.h
    ${ENGINE_DIR}/renderer-vulkan/MiscCVarStore.cpp
    ${ENGINE_DIR}/renderer-vulkan/MiscCVarStore.h
    ${ENGINE_DIR}/renderer-vulkan/RefAPI.cpp
    ${ENGINE_DIR}/renderer-vulkan/RefAPI.h
    ${ENGINE_DIR}/renderer-vulkan/Version.cpp
    ${ENGINE_DIR}/renderer-vulkan/Version.h
    ${ENGINE_DIR}/renderer-vulkan/Shared/Timer.cpp
    ${ENGINE_DIR}/renderer-vulkan/Shared/Timer.h
)
