// Auto-generated, do not modify

#ifndef VULKAN_LOADER_H
#define VULKAN_LOADER_H

#ifdef _MSC_VER
	#define VK_USE_PLATFORM_WIN32_KHR
#endif

#define VK_ENABLE_BETA_EXTENSIONS

#include "vulkan/vulkan.h"
#include "vulkan/vk_enum_string_helper.h"

extern PFN_vkCreateInstance vkCreateInstance;

extern PFN_vkDestroyInstance vkDestroyInstance;

extern PFN_vkEnumeratePhysicalDevices vkEnumeratePhysicalDevices;

extern PFN_vkGetPhysicalDeviceFeatures vkGetPhysicalDeviceFeatures;

extern PFN_vkGetPhysicalDeviceFormatProperties vkGetPhysicalDeviceFormatProperties;

extern PFN_vkGetPhysicalDeviceImageFormatProperties vkGetPhysicalDeviceImageFormatProperties;

extern PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties;

extern PFN_vkGetPhysicalDeviceQueueFamilyProperties vkGetPhysicalDeviceQueueFamilyProperties;

extern PFN_vkGetPhysicalDeviceMemoryProperties vkGetPhysicalDeviceMemoryProperties;

extern PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr;

extern PFN_vkGetDeviceProcAddr vkGetDeviceProcAddr;

extern PFN_vkCreateDevice vkCreateDevice;

extern PFN_vkDestroyDevice vkDestroyDevice;

extern PFN_vkEnumerateInstanceExtensionProperties vkEnumerateInstanceExtensionProperties;

extern PFN_vkEnumerateDeviceExtensionProperties vkEnumerateDeviceExtensionProperties;

extern PFN_vkEnumerateInstanceLayerProperties vkEnumerateInstanceLayerProperties;

extern PFN_vkEnumerateDeviceLayerProperties vkEnumerateDeviceLayerProperties;

extern PFN_vkGetDeviceQueue vkGetDeviceQueue;

extern PFN_vkQueueSubmit vkQueueSubmit;

extern PFN_vkQueueWaitIdle vkQueueWaitIdle;

extern PFN_vkDeviceWaitIdle vkDeviceWaitIdle;

extern PFN_vkAllocateMemory vkAllocateMemory;

extern PFN_vkFreeMemory vkFreeMemory;

extern PFN_vkMapMemory vkMapMemory;

extern PFN_vkUnmapMemory vkUnmapMemory;

extern PFN_vkFlushMappedMemoryRanges vkFlushMappedMemoryRanges;

extern PFN_vkInvalidateMappedMemoryRanges vkInvalidateMappedMemoryRanges;

extern PFN_vkGetDeviceMemoryCommitment vkGetDeviceMemoryCommitment;

extern PFN_vkBindBufferMemory vkBindBufferMemory;

extern PFN_vkBindImageMemory vkBindImageMemory;

extern PFN_vkGetBufferMemoryRequirements vkGetBufferMemoryRequirements;

extern PFN_vkGetImageMemoryRequirements vkGetImageMemoryRequirements;

extern PFN_vkGetImageSparseMemoryRequirements vkGetImageSparseMemoryRequirements;

extern PFN_vkGetPhysicalDeviceSparseImageFormatProperties vkGetPhysicalDeviceSparseImageFormatProperties;

extern PFN_vkQueueBindSparse vkQueueBindSparse;

extern PFN_vkCreateFence vkCreateFence;

extern PFN_vkDestroyFence vkDestroyFence;

extern PFN_vkResetFences vkResetFences;

extern PFN_vkGetFenceStatus vkGetFenceStatus;

extern PFN_vkWaitForFences vkWaitForFences;

extern PFN_vkCreateSemaphore vkCreateSemaphore;

extern PFN_vkDestroySemaphore vkDestroySemaphore;

extern PFN_vkCreateQueryPool vkCreateQueryPool;

extern PFN_vkDestroyQueryPool vkDestroyQueryPool;

extern PFN_vkGetQueryPoolResults vkGetQueryPoolResults;

extern PFN_vkCreateBuffer vkCreateBuffer;

extern PFN_vkDestroyBuffer vkDestroyBuffer;

extern PFN_vkCreateImage vkCreateImage;

extern PFN_vkDestroyImage vkDestroyImage;

extern PFN_vkGetImageSubresourceLayout vkGetImageSubresourceLayout;

extern PFN_vkCreateImageView vkCreateImageView;

extern PFN_vkDestroyImageView vkDestroyImageView;

extern PFN_vkCreateCommandPool vkCreateCommandPool;

extern PFN_vkDestroyCommandPool vkDestroyCommandPool;

extern PFN_vkResetCommandPool vkResetCommandPool;

extern PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers;

extern PFN_vkFreeCommandBuffers vkFreeCommandBuffers;

extern PFN_vkBeginCommandBuffer vkBeginCommandBuffer;

extern PFN_vkEndCommandBuffer vkEndCommandBuffer;

extern PFN_vkResetCommandBuffer vkResetCommandBuffer;

extern PFN_vkCmdCopyBuffer vkCmdCopyBuffer;

extern PFN_vkCmdCopyImage vkCmdCopyImage;

extern PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage;

extern PFN_vkCmdCopyImageToBuffer vkCmdCopyImageToBuffer;

extern PFN_vkCmdUpdateBuffer vkCmdUpdateBuffer;

extern PFN_vkCmdFillBuffer vkCmdFillBuffer;

extern PFN_vkCmdPipelineBarrier vkCmdPipelineBarrier;

extern PFN_vkCmdBeginQuery vkCmdBeginQuery;

extern PFN_vkCmdEndQuery vkCmdEndQuery;

extern PFN_vkCmdResetQueryPool vkCmdResetQueryPool;

extern PFN_vkCmdWriteTimestamp vkCmdWriteTimestamp;

extern PFN_vkCmdCopyQueryPoolResults vkCmdCopyQueryPoolResults;

extern PFN_vkCmdExecuteCommands vkCmdExecuteCommands;

extern PFN_vkCreateEvent vkCreateEvent;

extern PFN_vkDestroyEvent vkDestroyEvent;

extern PFN_vkGetEventStatus vkGetEventStatus;

extern PFN_vkSetEvent vkSetEvent;

extern PFN_vkResetEvent vkResetEvent;

extern PFN_vkCreateBufferView vkCreateBufferView;

extern PFN_vkDestroyBufferView vkDestroyBufferView;

extern PFN_vkCreateShaderModule vkCreateShaderModule;

extern PFN_vkDestroyShaderModule vkDestroyShaderModule;

extern PFN_vkCreatePipelineCache vkCreatePipelineCache;

extern PFN_vkDestroyPipelineCache vkDestroyPipelineCache;

extern PFN_vkGetPipelineCacheData vkGetPipelineCacheData;

extern PFN_vkMergePipelineCaches vkMergePipelineCaches;

extern PFN_vkCreateComputePipelines vkCreateComputePipelines;

extern PFN_vkDestroyPipeline vkDestroyPipeline;

extern PFN_vkCreatePipelineLayout vkCreatePipelineLayout;

extern PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout;

extern PFN_vkCreateSampler vkCreateSampler;

extern PFN_vkDestroySampler vkDestroySampler;

extern PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout;

extern PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout;

extern PFN_vkCreateDescriptorPool vkCreateDescriptorPool;

extern PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool;

extern PFN_vkResetDescriptorPool vkResetDescriptorPool;

extern PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets;

extern PFN_vkFreeDescriptorSets vkFreeDescriptorSets;

extern PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets;

extern PFN_vkCmdBindPipeline vkCmdBindPipeline;

extern PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets;

extern PFN_vkCmdClearColorImage vkCmdClearColorImage;

extern PFN_vkCmdDispatch vkCmdDispatch;

extern PFN_vkCmdDispatchIndirect vkCmdDispatchIndirect;

extern PFN_vkCmdSetEvent vkCmdSetEvent;

extern PFN_vkCmdResetEvent vkCmdResetEvent;

extern PFN_vkCmdWaitEvents vkCmdWaitEvents;

extern PFN_vkCmdPushConstants vkCmdPushConstants;

extern PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines;

extern PFN_vkCreateFramebuffer vkCreateFramebuffer;

extern PFN_vkDestroyFramebuffer vkDestroyFramebuffer;

extern PFN_vkCreateRenderPass vkCreateRenderPass;

extern PFN_vkDestroyRenderPass vkDestroyRenderPass;

extern PFN_vkGetRenderAreaGranularity vkGetRenderAreaGranularity;

extern PFN_vkCmdSetViewport vkCmdSetViewport;

extern PFN_vkCmdSetScissor vkCmdSetScissor;

extern PFN_vkCmdSetLineWidth vkCmdSetLineWidth;

extern PFN_vkCmdSetDepthBias vkCmdSetDepthBias;

extern PFN_vkCmdSetBlendConstants vkCmdSetBlendConstants;

extern PFN_vkCmdSetDepthBounds vkCmdSetDepthBounds;

extern PFN_vkCmdSetStencilCompareMask vkCmdSetStencilCompareMask;

extern PFN_vkCmdSetStencilWriteMask vkCmdSetStencilWriteMask;

extern PFN_vkCmdSetStencilReference vkCmdSetStencilReference;

extern PFN_vkCmdBindIndexBuffer vkCmdBindIndexBuffer;

extern PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers;

extern PFN_vkCmdDraw vkCmdDraw;

extern PFN_vkCmdDrawIndexed vkCmdDrawIndexed;

extern PFN_vkCmdDrawIndirect vkCmdDrawIndirect;

extern PFN_vkCmdDrawIndexedIndirect vkCmdDrawIndexedIndirect;

extern PFN_vkCmdBlitImage vkCmdBlitImage;

extern PFN_vkCmdClearDepthStencilImage vkCmdClearDepthStencilImage;

extern PFN_vkCmdClearAttachments vkCmdClearAttachments;

extern PFN_vkCmdResolveImage vkCmdResolveImage;

extern PFN_vkCmdBeginRenderPass vkCmdBeginRenderPass;

extern PFN_vkCmdNextSubpass vkCmdNextSubpass;

extern PFN_vkCmdEndRenderPass vkCmdEndRenderPass;

extern PFN_vkEnumerateInstanceVersion vkEnumerateInstanceVersion;

extern PFN_vkBindBufferMemory2 vkBindBufferMemory2;

extern PFN_vkBindImageMemory2 vkBindImageMemory2;

extern PFN_vkGetDeviceGroupPeerMemoryFeatures vkGetDeviceGroupPeerMemoryFeatures;

extern PFN_vkCmdSetDeviceMask vkCmdSetDeviceMask;

extern PFN_vkEnumeratePhysicalDeviceGroups vkEnumeratePhysicalDeviceGroups;

extern PFN_vkGetImageMemoryRequirements2 vkGetImageMemoryRequirements2;

extern PFN_vkGetBufferMemoryRequirements2 vkGetBufferMemoryRequirements2;

extern PFN_vkGetImageSparseMemoryRequirements2 vkGetImageSparseMemoryRequirements2;

extern PFN_vkGetPhysicalDeviceFeatures2 vkGetPhysicalDeviceFeatures2;

extern PFN_vkGetPhysicalDeviceProperties2 vkGetPhysicalDeviceProperties2;

extern PFN_vkGetPhysicalDeviceFormatProperties2 vkGetPhysicalDeviceFormatProperties2;

extern PFN_vkGetPhysicalDeviceImageFormatProperties2 vkGetPhysicalDeviceImageFormatProperties2;

extern PFN_vkGetPhysicalDeviceQueueFamilyProperties2 vkGetPhysicalDeviceQueueFamilyProperties2;

extern PFN_vkGetPhysicalDeviceMemoryProperties2 vkGetPhysicalDeviceMemoryProperties2;

extern PFN_vkGetPhysicalDeviceSparseImageFormatProperties2 vkGetPhysicalDeviceSparseImageFormatProperties2;

extern PFN_vkTrimCommandPool vkTrimCommandPool;

extern PFN_vkGetDeviceQueue2 vkGetDeviceQueue2;

extern PFN_vkGetPhysicalDeviceExternalBufferProperties vkGetPhysicalDeviceExternalBufferProperties;

extern PFN_vkGetPhysicalDeviceExternalFenceProperties vkGetPhysicalDeviceExternalFenceProperties;

extern PFN_vkGetPhysicalDeviceExternalSemaphoreProperties vkGetPhysicalDeviceExternalSemaphoreProperties;

extern PFN_vkCmdDispatchBase vkCmdDispatchBase;

extern PFN_vkCreateDescriptorUpdateTemplate vkCreateDescriptorUpdateTemplate;

extern PFN_vkDestroyDescriptorUpdateTemplate vkDestroyDescriptorUpdateTemplate;

extern PFN_vkUpdateDescriptorSetWithTemplate vkUpdateDescriptorSetWithTemplate;

extern PFN_vkGetDescriptorSetLayoutSupport vkGetDescriptorSetLayoutSupport;

extern PFN_vkCreateSamplerYcbcrConversion vkCreateSamplerYcbcrConversion;

extern PFN_vkDestroySamplerYcbcrConversion vkDestroySamplerYcbcrConversion;

extern PFN_vkResetQueryPool vkResetQueryPool;

extern PFN_vkGetSemaphoreCounterValue vkGetSemaphoreCounterValue;

extern PFN_vkWaitSemaphores vkWaitSemaphores;

extern PFN_vkSignalSemaphore vkSignalSemaphore;

extern PFN_vkGetBufferDeviceAddress vkGetBufferDeviceAddress;

extern PFN_vkGetBufferOpaqueCaptureAddress vkGetBufferOpaqueCaptureAddress;

extern PFN_vkGetDeviceMemoryOpaqueCaptureAddress vkGetDeviceMemoryOpaqueCaptureAddress;

extern PFN_vkCmdDrawIndirectCount vkCmdDrawIndirectCount;

extern PFN_vkCmdDrawIndexedIndirectCount vkCmdDrawIndexedIndirectCount;

extern PFN_vkCreateRenderPass2 vkCreateRenderPass2;

extern PFN_vkCmdBeginRenderPass2 vkCmdBeginRenderPass2;

extern PFN_vkCmdNextSubpass2 vkCmdNextSubpass2;

extern PFN_vkCmdEndRenderPass2 vkCmdEndRenderPass2;

extern PFN_vkGetPhysicalDeviceToolProperties vkGetPhysicalDeviceToolProperties;

extern PFN_vkCreatePrivateDataSlot vkCreatePrivateDataSlot;

extern PFN_vkDestroyPrivateDataSlot vkDestroyPrivateDataSlot;

extern PFN_vkSetPrivateData vkSetPrivateData;

extern PFN_vkGetPrivateData vkGetPrivateData;

extern PFN_vkCmdPipelineBarrier2 vkCmdPipelineBarrier2;

extern PFN_vkCmdWriteTimestamp2 vkCmdWriteTimestamp2;

extern PFN_vkQueueSubmit2 vkQueueSubmit2;

extern PFN_vkCmdCopyBuffer2 vkCmdCopyBuffer2;

extern PFN_vkCmdCopyImage2 vkCmdCopyImage2;

extern PFN_vkCmdCopyBufferToImage2 vkCmdCopyBufferToImage2;

extern PFN_vkCmdCopyImageToBuffer2 vkCmdCopyImageToBuffer2;

extern PFN_vkGetDeviceBufferMemoryRequirements vkGetDeviceBufferMemoryRequirements;

extern PFN_vkGetDeviceImageMemoryRequirements vkGetDeviceImageMemoryRequirements;

extern PFN_vkGetDeviceImageSparseMemoryRequirements vkGetDeviceImageSparseMemoryRequirements;

extern PFN_vkCmdSetEvent2 vkCmdSetEvent2;

extern PFN_vkCmdResetEvent2 vkCmdResetEvent2;

extern PFN_vkCmdWaitEvents2 vkCmdWaitEvents2;

extern PFN_vkCmdBlitImage2 vkCmdBlitImage2;

extern PFN_vkCmdResolveImage2 vkCmdResolveImage2;

extern PFN_vkCmdBeginRendering vkCmdBeginRendering;

extern PFN_vkCmdEndRendering vkCmdEndRendering;

extern PFN_vkCmdSetCullMode vkCmdSetCullMode;

extern PFN_vkCmdSetFrontFace vkCmdSetFrontFace;

extern PFN_vkCmdSetPrimitiveTopology vkCmdSetPrimitiveTopology;

extern PFN_vkCmdSetViewportWithCount vkCmdSetViewportWithCount;

extern PFN_vkCmdSetScissorWithCount vkCmdSetScissorWithCount;

extern PFN_vkCmdBindVertexBuffers2 vkCmdBindVertexBuffers2;

extern PFN_vkCmdSetDepthTestEnable vkCmdSetDepthTestEnable;

extern PFN_vkCmdSetDepthWriteEnable vkCmdSetDepthWriteEnable;

extern PFN_vkCmdSetDepthCompareOp vkCmdSetDepthCompareOp;

extern PFN_vkCmdSetDepthBoundsTestEnable vkCmdSetDepthBoundsTestEnable;

extern PFN_vkCmdSetStencilTestEnable vkCmdSetStencilTestEnable;

extern PFN_vkCmdSetStencilOp vkCmdSetStencilOp;

extern PFN_vkCmdSetRasterizerDiscardEnable vkCmdSetRasterizerDiscardEnable;

extern PFN_vkCmdSetDepthBiasEnable vkCmdSetDepthBiasEnable;

extern PFN_vkCmdSetPrimitiveRestartEnable vkCmdSetPrimitiveRestartEnable;

extern PFN_vkMapMemory2 vkMapMemory2;

extern PFN_vkUnmapMemory2 vkUnmapMemory2;

extern PFN_vkGetDeviceImageSubresourceLayout vkGetDeviceImageSubresourceLayout;

extern PFN_vkGetImageSubresourceLayout2 vkGetImageSubresourceLayout2;

extern PFN_vkCopyMemoryToImage vkCopyMemoryToImage;

extern PFN_vkCopyImageToMemory vkCopyImageToMemory;

extern PFN_vkCopyImageToImage vkCopyImageToImage;

extern PFN_vkTransitionImageLayout vkTransitionImageLayout;

extern PFN_vkCmdPushDescriptorSet vkCmdPushDescriptorSet;

extern PFN_vkCmdPushDescriptorSetWithTemplate vkCmdPushDescriptorSetWithTemplate;

extern PFN_vkCmdBindDescriptorSets2 vkCmdBindDescriptorSets2;

extern PFN_vkCmdPushConstants2 vkCmdPushConstants2;

extern PFN_vkCmdPushDescriptorSet2 vkCmdPushDescriptorSet2;

extern PFN_vkCmdPushDescriptorSetWithTemplate2 vkCmdPushDescriptorSetWithTemplate2;

extern PFN_vkCmdSetLineStipple vkCmdSetLineStipple;

extern PFN_vkCmdBindIndexBuffer2 vkCmdBindIndexBuffer2;

extern PFN_vkGetRenderingAreaGranularity vkGetRenderingAreaGranularity;

extern PFN_vkCmdSetRenderingAttachmentLocations vkCmdSetRenderingAttachmentLocations;

extern PFN_vkCmdSetRenderingInputAttachmentIndices vkCmdSetRenderingInputAttachmentIndices;

extern PFN_vkDestroySurfaceKHR vkDestroySurfaceKHR;

extern PFN_vkGetPhysicalDeviceSurfaceSupportKHR vkGetPhysicalDeviceSurfaceSupportKHR;

extern PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR vkGetPhysicalDeviceSurfaceCapabilitiesKHR;

extern PFN_vkGetPhysicalDeviceSurfaceFormatsKHR vkGetPhysicalDeviceSurfaceFormatsKHR;

extern PFN_vkGetPhysicalDeviceSurfacePresentModesKHR vkGetPhysicalDeviceSurfacePresentModesKHR;

extern PFN_vkCreateSwapchainKHR vkCreateSwapchainKHR;

extern PFN_vkDestroySwapchainKHR vkDestroySwapchainKHR;

extern PFN_vkGetSwapchainImagesKHR vkGetSwapchainImagesKHR;

extern PFN_vkAcquireNextImageKHR vkAcquireNextImageKHR;

extern PFN_vkQueuePresentKHR vkQueuePresentKHR;

extern PFN_vkGetDeviceGroupPresentCapabilitiesKHR vkGetDeviceGroupPresentCapabilitiesKHR;

extern PFN_vkGetDeviceGroupSurfacePresentModesKHR vkGetDeviceGroupSurfacePresentModesKHR;

extern PFN_vkGetPhysicalDevicePresentRectanglesKHR vkGetPhysicalDevicePresentRectanglesKHR;

extern PFN_vkAcquireNextImage2KHR vkAcquireNextImage2KHR;

extern PFN_vkGetPhysicalDeviceDisplayPropertiesKHR vkGetPhysicalDeviceDisplayPropertiesKHR;

extern PFN_vkGetPhysicalDeviceDisplayPlanePropertiesKHR vkGetPhysicalDeviceDisplayPlanePropertiesKHR;

extern PFN_vkGetDisplayPlaneSupportedDisplaysKHR vkGetDisplayPlaneSupportedDisplaysKHR;

extern PFN_vkGetDisplayModePropertiesKHR vkGetDisplayModePropertiesKHR;

extern PFN_vkCreateDisplayModeKHR vkCreateDisplayModeKHR;

extern PFN_vkGetDisplayPlaneCapabilitiesKHR vkGetDisplayPlaneCapabilitiesKHR;

extern PFN_vkCreateDisplayPlaneSurfaceKHR vkCreateDisplayPlaneSurfaceKHR;

extern PFN_vkCreateSharedSwapchainsKHR vkCreateSharedSwapchainsKHR;

extern PFN_vkGetPhysicalDeviceVideoCapabilitiesKHR vkGetPhysicalDeviceVideoCapabilitiesKHR;

extern PFN_vkGetPhysicalDeviceVideoFormatPropertiesKHR vkGetPhysicalDeviceVideoFormatPropertiesKHR;

extern PFN_vkCreateVideoSessionKHR vkCreateVideoSessionKHR;

extern PFN_vkDestroyVideoSessionKHR vkDestroyVideoSessionKHR;

extern PFN_vkGetVideoSessionMemoryRequirementsKHR vkGetVideoSessionMemoryRequirementsKHR;

extern PFN_vkBindVideoSessionMemoryKHR vkBindVideoSessionMemoryKHR;

extern PFN_vkCreateVideoSessionParametersKHR vkCreateVideoSessionParametersKHR;

extern PFN_vkUpdateVideoSessionParametersKHR vkUpdateVideoSessionParametersKHR;

extern PFN_vkDestroyVideoSessionParametersKHR vkDestroyVideoSessionParametersKHR;

extern PFN_vkCmdBeginVideoCodingKHR vkCmdBeginVideoCodingKHR;

extern PFN_vkCmdEndVideoCodingKHR vkCmdEndVideoCodingKHR;

extern PFN_vkCmdControlVideoCodingKHR vkCmdControlVideoCodingKHR;

extern PFN_vkCmdDecodeVideoKHR vkCmdDecodeVideoKHR;

extern PFN_vkCmdBeginRenderingKHR vkCmdBeginRenderingKHR;

extern PFN_vkCmdEndRenderingKHR vkCmdEndRenderingKHR;

extern PFN_vkGetPhysicalDeviceFeatures2KHR vkGetPhysicalDeviceFeatures2KHR;

extern PFN_vkGetPhysicalDeviceProperties2KHR vkGetPhysicalDeviceProperties2KHR;

extern PFN_vkGetPhysicalDeviceFormatProperties2KHR vkGetPhysicalDeviceFormatProperties2KHR;

extern PFN_vkGetPhysicalDeviceImageFormatProperties2KHR vkGetPhysicalDeviceImageFormatProperties2KHR;

extern PFN_vkGetPhysicalDeviceQueueFamilyProperties2KHR vkGetPhysicalDeviceQueueFamilyProperties2KHR;

extern PFN_vkGetPhysicalDeviceMemoryProperties2KHR vkGetPhysicalDeviceMemoryProperties2KHR;

extern PFN_vkGetPhysicalDeviceSparseImageFormatProperties2KHR vkGetPhysicalDeviceSparseImageFormatProperties2KHR;

extern PFN_vkGetDeviceGroupPeerMemoryFeaturesKHR vkGetDeviceGroupPeerMemoryFeaturesKHR;

extern PFN_vkCmdSetDeviceMaskKHR vkCmdSetDeviceMaskKHR;

extern PFN_vkCmdDispatchBaseKHR vkCmdDispatchBaseKHR;

extern PFN_vkTrimCommandPoolKHR vkTrimCommandPoolKHR;

extern PFN_vkEnumeratePhysicalDeviceGroupsKHR vkEnumeratePhysicalDeviceGroupsKHR;

extern PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR vkGetPhysicalDeviceExternalBufferPropertiesKHR;

extern PFN_vkGetMemoryFdKHR vkGetMemoryFdKHR;

extern PFN_vkGetMemoryFdPropertiesKHR vkGetMemoryFdPropertiesKHR;

extern PFN_vkGetPhysicalDeviceExternalSemaphorePropertiesKHR vkGetPhysicalDeviceExternalSemaphorePropertiesKHR;

extern PFN_vkImportSemaphoreFdKHR vkImportSemaphoreFdKHR;

extern PFN_vkGetSemaphoreFdKHR vkGetSemaphoreFdKHR;

extern PFN_vkCmdPushDescriptorSetKHR vkCmdPushDescriptorSetKHR;

extern PFN_vkCmdPushDescriptorSetWithTemplateKHR vkCmdPushDescriptorSetWithTemplateKHR;

extern PFN_vkCreateDescriptorUpdateTemplateKHR vkCreateDescriptorUpdateTemplateKHR;

extern PFN_vkDestroyDescriptorUpdateTemplateKHR vkDestroyDescriptorUpdateTemplateKHR;

extern PFN_vkUpdateDescriptorSetWithTemplateKHR vkUpdateDescriptorSetWithTemplateKHR;

extern PFN_vkCreateRenderPass2KHR vkCreateRenderPass2KHR;

extern PFN_vkCmdBeginRenderPass2KHR vkCmdBeginRenderPass2KHR;

extern PFN_vkCmdNextSubpass2KHR vkCmdNextSubpass2KHR;

extern PFN_vkCmdEndRenderPass2KHR vkCmdEndRenderPass2KHR;

extern PFN_vkGetSwapchainStatusKHR vkGetSwapchainStatusKHR;

extern PFN_vkGetPhysicalDeviceExternalFencePropertiesKHR vkGetPhysicalDeviceExternalFencePropertiesKHR;

extern PFN_vkImportFenceFdKHR vkImportFenceFdKHR;

extern PFN_vkGetFenceFdKHR vkGetFenceFdKHR;

extern PFN_vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR;

extern PFN_vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR;

extern PFN_vkAcquireProfilingLockKHR vkAcquireProfilingLockKHR;

extern PFN_vkReleaseProfilingLockKHR vkReleaseProfilingLockKHR;

extern PFN_vkGetPhysicalDeviceSurfaceCapabilities2KHR vkGetPhysicalDeviceSurfaceCapabilities2KHR;

extern PFN_vkGetPhysicalDeviceSurfaceFormats2KHR vkGetPhysicalDeviceSurfaceFormats2KHR;

extern PFN_vkGetPhysicalDeviceDisplayProperties2KHR vkGetPhysicalDeviceDisplayProperties2KHR;

extern PFN_vkGetPhysicalDeviceDisplayPlaneProperties2KHR vkGetPhysicalDeviceDisplayPlaneProperties2KHR;

extern PFN_vkGetDisplayModeProperties2KHR vkGetDisplayModeProperties2KHR;

extern PFN_vkGetDisplayPlaneCapabilities2KHR vkGetDisplayPlaneCapabilities2KHR;

extern PFN_vkGetImageMemoryRequirements2KHR vkGetImageMemoryRequirements2KHR;

extern PFN_vkGetBufferMemoryRequirements2KHR vkGetBufferMemoryRequirements2KHR;

extern PFN_vkGetImageSparseMemoryRequirements2KHR vkGetImageSparseMemoryRequirements2KHR;

extern PFN_vkCreateSamplerYcbcrConversionKHR vkCreateSamplerYcbcrConversionKHR;

extern PFN_vkDestroySamplerYcbcrConversionKHR vkDestroySamplerYcbcrConversionKHR;

extern PFN_vkBindBufferMemory2KHR vkBindBufferMemory2KHR;

extern PFN_vkBindImageMemory2KHR vkBindImageMemory2KHR;

extern PFN_vkGetDescriptorSetLayoutSupportKHR vkGetDescriptorSetLayoutSupportKHR;

extern PFN_vkCmdDrawIndirectCountKHR vkCmdDrawIndirectCountKHR;

extern PFN_vkCmdDrawIndexedIndirectCountKHR vkCmdDrawIndexedIndirectCountKHR;

extern PFN_vkGetSemaphoreCounterValueKHR vkGetSemaphoreCounterValueKHR;

extern PFN_vkWaitSemaphoresKHR vkWaitSemaphoresKHR;

extern PFN_vkSignalSemaphoreKHR vkSignalSemaphoreKHR;

extern PFN_vkGetPhysicalDeviceFragmentShadingRatesKHR vkGetPhysicalDeviceFragmentShadingRatesKHR;

extern PFN_vkCmdSetFragmentShadingRateKHR vkCmdSetFragmentShadingRateKHR;

extern PFN_vkCmdSetRenderingAttachmentLocationsKHR vkCmdSetRenderingAttachmentLocationsKHR;

extern PFN_vkCmdSetRenderingInputAttachmentIndicesKHR vkCmdSetRenderingInputAttachmentIndicesKHR;

extern PFN_vkWaitForPresentKHR vkWaitForPresentKHR;

extern PFN_vkGetBufferDeviceAddressKHR vkGetBufferDeviceAddressKHR;

extern PFN_vkGetBufferOpaqueCaptureAddressKHR vkGetBufferOpaqueCaptureAddressKHR;

extern PFN_vkGetDeviceMemoryOpaqueCaptureAddressKHR vkGetDeviceMemoryOpaqueCaptureAddressKHR;

extern PFN_vkCreateDeferredOperationKHR vkCreateDeferredOperationKHR;

extern PFN_vkDestroyDeferredOperationKHR vkDestroyDeferredOperationKHR;

extern PFN_vkGetDeferredOperationMaxConcurrencyKHR vkGetDeferredOperationMaxConcurrencyKHR;

extern PFN_vkGetDeferredOperationResultKHR vkGetDeferredOperationResultKHR;

extern PFN_vkDeferredOperationJoinKHR vkDeferredOperationJoinKHR;

extern PFN_vkGetPipelineExecutablePropertiesKHR vkGetPipelineExecutablePropertiesKHR;

extern PFN_vkGetPipelineExecutableStatisticsKHR vkGetPipelineExecutableStatisticsKHR;

extern PFN_vkGetPipelineExecutableInternalRepresentationsKHR vkGetPipelineExecutableInternalRepresentationsKHR;

extern PFN_vkMapMemory2KHR vkMapMemory2KHR;

extern PFN_vkUnmapMemory2KHR vkUnmapMemory2KHR;

extern PFN_vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR;

extern PFN_vkGetEncodedVideoSessionParametersKHR vkGetEncodedVideoSessionParametersKHR;

extern PFN_vkCmdEncodeVideoKHR vkCmdEncodeVideoKHR;

extern PFN_vkCmdSetEvent2KHR vkCmdSetEvent2KHR;

extern PFN_vkCmdResetEvent2KHR vkCmdResetEvent2KHR;

extern PFN_vkCmdWaitEvents2KHR vkCmdWaitEvents2KHR;

extern PFN_vkCmdPipelineBarrier2KHR vkCmdPipelineBarrier2KHR;

extern PFN_vkCmdWriteTimestamp2KHR vkCmdWriteTimestamp2KHR;

extern PFN_vkQueueSubmit2KHR vkQueueSubmit2KHR;

extern PFN_vkCmdCopyBuffer2KHR vkCmdCopyBuffer2KHR;

extern PFN_vkCmdCopyImage2KHR vkCmdCopyImage2KHR;

extern PFN_vkCmdCopyBufferToImage2KHR vkCmdCopyBufferToImage2KHR;

extern PFN_vkCmdCopyImageToBuffer2KHR vkCmdCopyImageToBuffer2KHR;

extern PFN_vkCmdBlitImage2KHR vkCmdBlitImage2KHR;

extern PFN_vkCmdResolveImage2KHR vkCmdResolveImage2KHR;

extern PFN_vkCmdTraceRaysIndirect2KHR vkCmdTraceRaysIndirect2KHR;

extern PFN_vkGetDeviceBufferMemoryRequirementsKHR vkGetDeviceBufferMemoryRequirementsKHR;

extern PFN_vkGetDeviceImageMemoryRequirementsKHR vkGetDeviceImageMemoryRequirementsKHR;

extern PFN_vkGetDeviceImageSparseMemoryRequirementsKHR vkGetDeviceImageSparseMemoryRequirementsKHR;

extern PFN_vkCmdBindIndexBuffer2KHR vkCmdBindIndexBuffer2KHR;

extern PFN_vkGetRenderingAreaGranularityKHR vkGetRenderingAreaGranularityKHR;

extern PFN_vkGetDeviceImageSubresourceLayoutKHR vkGetDeviceImageSubresourceLayoutKHR;

extern PFN_vkGetImageSubresourceLayout2KHR vkGetImageSubresourceLayout2KHR;

extern PFN_vkWaitForPresent2KHR vkWaitForPresent2KHR;

extern PFN_vkCreatePipelineBinariesKHR vkCreatePipelineBinariesKHR;

extern PFN_vkDestroyPipelineBinaryKHR vkDestroyPipelineBinaryKHR;

extern PFN_vkGetPipelineKeyKHR vkGetPipelineKeyKHR;

extern PFN_vkGetPipelineBinaryDataKHR vkGetPipelineBinaryDataKHR;

extern PFN_vkReleaseCapturedPipelineDataKHR vkReleaseCapturedPipelineDataKHR;

extern PFN_vkReleaseSwapchainImagesKHR vkReleaseSwapchainImagesKHR;

extern PFN_vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR;

extern PFN_vkCmdSetLineStippleKHR vkCmdSetLineStippleKHR;

extern PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsKHR vkGetPhysicalDeviceCalibrateableTimeDomainsKHR;

extern PFN_vkGetCalibratedTimestampsKHR vkGetCalibratedTimestampsKHR;

extern PFN_vkCmdBindDescriptorSets2KHR vkCmdBindDescriptorSets2KHR;

extern PFN_vkCmdPushConstants2KHR vkCmdPushConstants2KHR;

extern PFN_vkCmdPushDescriptorSet2KHR vkCmdPushDescriptorSet2KHR;

extern PFN_vkCmdPushDescriptorSetWithTemplate2KHR vkCmdPushDescriptorSetWithTemplate2KHR;

extern PFN_vkCmdSetDescriptorBufferOffsets2EXT vkCmdSetDescriptorBufferOffsets2EXT;

extern PFN_vkCmdBindDescriptorBufferEmbeddedSamplers2EXT vkCmdBindDescriptorBufferEmbeddedSamplers2EXT;

extern PFN_vkCmdCopyMemoryIndirectKHR vkCmdCopyMemoryIndirectKHR;

extern PFN_vkCmdCopyMemoryToImageIndirectKHR vkCmdCopyMemoryToImageIndirectKHR;

extern PFN_vkCmdEndRendering2KHR vkCmdEndRendering2KHR;

extern PFN_vkCreateDebugReportCallbackEXT vkCreateDebugReportCallbackEXT;

extern PFN_vkDestroyDebugReportCallbackEXT vkDestroyDebugReportCallbackEXT;

extern PFN_vkDebugReportMessageEXT vkDebugReportMessageEXT;

extern PFN_vkDebugMarkerSetObjectTagEXT vkDebugMarkerSetObjectTagEXT;

extern PFN_vkDebugMarkerSetObjectNameEXT vkDebugMarkerSetObjectNameEXT;

extern PFN_vkCmdDebugMarkerBeginEXT vkCmdDebugMarkerBeginEXT;

extern PFN_vkCmdDebugMarkerEndEXT vkCmdDebugMarkerEndEXT;

extern PFN_vkCmdDebugMarkerInsertEXT vkCmdDebugMarkerInsertEXT;

extern PFN_vkCmdBindTransformFeedbackBuffersEXT vkCmdBindTransformFeedbackBuffersEXT;

extern PFN_vkCmdBeginTransformFeedbackEXT vkCmdBeginTransformFeedbackEXT;

extern PFN_vkCmdEndTransformFeedbackEXT vkCmdEndTransformFeedbackEXT;

extern PFN_vkCmdBeginQueryIndexedEXT vkCmdBeginQueryIndexedEXT;

extern PFN_vkCmdEndQueryIndexedEXT vkCmdEndQueryIndexedEXT;

extern PFN_vkCmdDrawIndirectByteCountEXT vkCmdDrawIndirectByteCountEXT;

extern PFN_vkCreateCuModuleNVX vkCreateCuModuleNVX;

extern PFN_vkCreateCuFunctionNVX vkCreateCuFunctionNVX;

extern PFN_vkDestroyCuModuleNVX vkDestroyCuModuleNVX;

extern PFN_vkDestroyCuFunctionNVX vkDestroyCuFunctionNVX;

extern PFN_vkCmdCuLaunchKernelNVX vkCmdCuLaunchKernelNVX;

extern PFN_vkGetImageViewHandleNVX vkGetImageViewHandleNVX;

extern PFN_vkGetImageViewHandle64NVX vkGetImageViewHandle64NVX;

extern PFN_vkGetImageViewAddressNVX vkGetImageViewAddressNVX;

extern PFN_vkGetDeviceCombinedImageSamplerIndexNVX vkGetDeviceCombinedImageSamplerIndexNVX;

extern PFN_vkCmdDrawIndirectCountAMD vkCmdDrawIndirectCountAMD;

extern PFN_vkCmdDrawIndexedIndirectCountAMD vkCmdDrawIndexedIndirectCountAMD;

extern PFN_vkGetShaderInfoAMD vkGetShaderInfoAMD;

extern PFN_vkGetPhysicalDeviceExternalImageFormatPropertiesNV vkGetPhysicalDeviceExternalImageFormatPropertiesNV;

extern PFN_vkCmdBeginConditionalRenderingEXT vkCmdBeginConditionalRenderingEXT;

extern PFN_vkCmdEndConditionalRenderingEXT vkCmdEndConditionalRenderingEXT;

extern PFN_vkCmdSetViewportWScalingNV vkCmdSetViewportWScalingNV;

extern PFN_vkReleaseDisplayEXT vkReleaseDisplayEXT;

extern PFN_vkGetPhysicalDeviceSurfaceCapabilities2EXT vkGetPhysicalDeviceSurfaceCapabilities2EXT;

extern PFN_vkDisplayPowerControlEXT vkDisplayPowerControlEXT;

extern PFN_vkRegisterDeviceEventEXT vkRegisterDeviceEventEXT;

extern PFN_vkRegisterDisplayEventEXT vkRegisterDisplayEventEXT;

extern PFN_vkGetSwapchainCounterEXT vkGetSwapchainCounterEXT;

extern PFN_vkGetRefreshCycleDurationGOOGLE vkGetRefreshCycleDurationGOOGLE;

extern PFN_vkGetPastPresentationTimingGOOGLE vkGetPastPresentationTimingGOOGLE;

extern PFN_vkCmdSetDiscardRectangleEXT vkCmdSetDiscardRectangleEXT;

extern PFN_vkCmdSetDiscardRectangleEnableEXT vkCmdSetDiscardRectangleEnableEXT;

extern PFN_vkCmdSetDiscardRectangleModeEXT vkCmdSetDiscardRectangleModeEXT;

extern PFN_vkSetHdrMetadataEXT vkSetHdrMetadataEXT;

extern PFN_vkSetDebugUtilsObjectNameEXT vkSetDebugUtilsObjectNameEXT;

extern PFN_vkSetDebugUtilsObjectTagEXT vkSetDebugUtilsObjectTagEXT;

extern PFN_vkQueueBeginDebugUtilsLabelEXT vkQueueBeginDebugUtilsLabelEXT;

extern PFN_vkQueueEndDebugUtilsLabelEXT vkQueueEndDebugUtilsLabelEXT;

extern PFN_vkQueueInsertDebugUtilsLabelEXT vkQueueInsertDebugUtilsLabelEXT;

extern PFN_vkCmdBeginDebugUtilsLabelEXT vkCmdBeginDebugUtilsLabelEXT;

extern PFN_vkCmdEndDebugUtilsLabelEXT vkCmdEndDebugUtilsLabelEXT;

extern PFN_vkCmdInsertDebugUtilsLabelEXT vkCmdInsertDebugUtilsLabelEXT;

extern PFN_vkCreateDebugUtilsMessengerEXT vkCreateDebugUtilsMessengerEXT;

extern PFN_vkDestroyDebugUtilsMessengerEXT vkDestroyDebugUtilsMessengerEXT;

extern PFN_vkSubmitDebugUtilsMessageEXT vkSubmitDebugUtilsMessageEXT;

extern PFN_vkWriteSamplerDescriptorsEXT vkWriteSamplerDescriptorsEXT;

extern PFN_vkWriteResourceDescriptorsEXT vkWriteResourceDescriptorsEXT;

extern PFN_vkCmdBindSamplerHeapEXT vkCmdBindSamplerHeapEXT;

extern PFN_vkCmdBindResourceHeapEXT vkCmdBindResourceHeapEXT;

extern PFN_vkCmdPushDataEXT vkCmdPushDataEXT;

extern PFN_vkGetImageOpaqueCaptureDataEXT vkGetImageOpaqueCaptureDataEXT;

extern PFN_vkGetPhysicalDeviceDescriptorSizeEXT vkGetPhysicalDeviceDescriptorSizeEXT;

extern PFN_vkRegisterCustomBorderColorEXT vkRegisterCustomBorderColorEXT;

extern PFN_vkUnregisterCustomBorderColorEXT vkUnregisterCustomBorderColorEXT;

extern PFN_vkGetTensorOpaqueCaptureDataARM vkGetTensorOpaqueCaptureDataARM;

extern PFN_vkCmdSetSampleLocationsEXT vkCmdSetSampleLocationsEXT;

extern PFN_vkGetPhysicalDeviceMultisamplePropertiesEXT vkGetPhysicalDeviceMultisamplePropertiesEXT;

extern PFN_vkGetImageDrmFormatModifierPropertiesEXT vkGetImageDrmFormatModifierPropertiesEXT;

extern PFN_vkCreateValidationCacheEXT vkCreateValidationCacheEXT;

extern PFN_vkDestroyValidationCacheEXT vkDestroyValidationCacheEXT;

extern PFN_vkMergeValidationCachesEXT vkMergeValidationCachesEXT;

extern PFN_vkGetValidationCacheDataEXT vkGetValidationCacheDataEXT;

extern PFN_vkCmdBindShadingRateImageNV vkCmdBindShadingRateImageNV;

extern PFN_vkCmdSetViewportShadingRatePaletteNV vkCmdSetViewportShadingRatePaletteNV;

extern PFN_vkCmdSetCoarseSampleOrderNV vkCmdSetCoarseSampleOrderNV;

extern PFN_vkCreateAccelerationStructureNV vkCreateAccelerationStructureNV;

extern PFN_vkDestroyAccelerationStructureNV vkDestroyAccelerationStructureNV;

extern PFN_vkGetAccelerationStructureMemoryRequirementsNV vkGetAccelerationStructureMemoryRequirementsNV;

extern PFN_vkBindAccelerationStructureMemoryNV vkBindAccelerationStructureMemoryNV;

extern PFN_vkCmdBuildAccelerationStructureNV vkCmdBuildAccelerationStructureNV;

extern PFN_vkCmdCopyAccelerationStructureNV vkCmdCopyAccelerationStructureNV;

extern PFN_vkCmdTraceRaysNV vkCmdTraceRaysNV;

extern PFN_vkCreateRayTracingPipelinesNV vkCreateRayTracingPipelinesNV;

extern PFN_vkGetRayTracingShaderGroupHandlesKHR vkGetRayTracingShaderGroupHandlesKHR;

extern PFN_vkGetRayTracingShaderGroupHandlesNV vkGetRayTracingShaderGroupHandlesNV;

extern PFN_vkGetAccelerationStructureHandleNV vkGetAccelerationStructureHandleNV;

extern PFN_vkCmdWriteAccelerationStructuresPropertiesNV vkCmdWriteAccelerationStructuresPropertiesNV;

extern PFN_vkCompileDeferredNV vkCompileDeferredNV;

extern PFN_vkGetMemoryHostPointerPropertiesEXT vkGetMemoryHostPointerPropertiesEXT;

extern PFN_vkCmdWriteBufferMarkerAMD vkCmdWriteBufferMarkerAMD;

extern PFN_vkCmdWriteBufferMarker2AMD vkCmdWriteBufferMarker2AMD;

extern PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsEXT vkGetPhysicalDeviceCalibrateableTimeDomainsEXT;

extern PFN_vkGetCalibratedTimestampsEXT vkGetCalibratedTimestampsEXT;

extern PFN_vkCmdDrawMeshTasksNV vkCmdDrawMeshTasksNV;

extern PFN_vkCmdDrawMeshTasksIndirectNV vkCmdDrawMeshTasksIndirectNV;

extern PFN_vkCmdDrawMeshTasksIndirectCountNV vkCmdDrawMeshTasksIndirectCountNV;

extern PFN_vkCmdSetExclusiveScissorEnableNV vkCmdSetExclusiveScissorEnableNV;

extern PFN_vkCmdSetExclusiveScissorNV vkCmdSetExclusiveScissorNV;

extern PFN_vkCmdSetCheckpointNV vkCmdSetCheckpointNV;

extern PFN_vkGetQueueCheckpointDataNV vkGetQueueCheckpointDataNV;

extern PFN_vkGetQueueCheckpointData2NV vkGetQueueCheckpointData2NV;

extern PFN_vkSetSwapchainPresentTimingQueueSizeEXT vkSetSwapchainPresentTimingQueueSizeEXT;

extern PFN_vkGetSwapchainTimingPropertiesEXT vkGetSwapchainTimingPropertiesEXT;

extern PFN_vkGetSwapchainTimeDomainPropertiesEXT vkGetSwapchainTimeDomainPropertiesEXT;

extern PFN_vkGetPastPresentationTimingEXT vkGetPastPresentationTimingEXT;

extern PFN_vkInitializePerformanceApiINTEL vkInitializePerformanceApiINTEL;

extern PFN_vkUninitializePerformanceApiINTEL vkUninitializePerformanceApiINTEL;

extern PFN_vkCmdSetPerformanceMarkerINTEL vkCmdSetPerformanceMarkerINTEL;

extern PFN_vkCmdSetPerformanceStreamMarkerINTEL vkCmdSetPerformanceStreamMarkerINTEL;

extern PFN_vkCmdSetPerformanceOverrideINTEL vkCmdSetPerformanceOverrideINTEL;

extern PFN_vkAcquirePerformanceConfigurationINTEL vkAcquirePerformanceConfigurationINTEL;

extern PFN_vkReleasePerformanceConfigurationINTEL vkReleasePerformanceConfigurationINTEL;

extern PFN_vkQueueSetPerformanceConfigurationINTEL vkQueueSetPerformanceConfigurationINTEL;

extern PFN_vkGetPerformanceParameterINTEL vkGetPerformanceParameterINTEL;

extern PFN_vkSetLocalDimmingAMD vkSetLocalDimmingAMD;

extern PFN_vkGetBufferDeviceAddressEXT vkGetBufferDeviceAddressEXT;

extern PFN_vkGetPhysicalDeviceToolPropertiesEXT vkGetPhysicalDeviceToolPropertiesEXT;

extern PFN_vkGetPhysicalDeviceCooperativeMatrixPropertiesNV vkGetPhysicalDeviceCooperativeMatrixPropertiesNV;

extern PFN_vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV;

extern PFN_vkCreateHeadlessSurfaceEXT vkCreateHeadlessSurfaceEXT;

extern PFN_vkCmdSetLineStippleEXT vkCmdSetLineStippleEXT;

extern PFN_vkResetQueryPoolEXT vkResetQueryPoolEXT;

extern PFN_vkCmdSetCullModeEXT vkCmdSetCullModeEXT;

extern PFN_vkCmdSetFrontFaceEXT vkCmdSetFrontFaceEXT;

extern PFN_vkCmdSetPrimitiveTopologyEXT vkCmdSetPrimitiveTopologyEXT;

extern PFN_vkCmdSetViewportWithCountEXT vkCmdSetViewportWithCountEXT;

extern PFN_vkCmdSetScissorWithCountEXT vkCmdSetScissorWithCountEXT;

extern PFN_vkCmdBindVertexBuffers2EXT vkCmdBindVertexBuffers2EXT;

extern PFN_vkCmdSetDepthTestEnableEXT vkCmdSetDepthTestEnableEXT;

extern PFN_vkCmdSetDepthWriteEnableEXT vkCmdSetDepthWriteEnableEXT;

extern PFN_vkCmdSetDepthCompareOpEXT vkCmdSetDepthCompareOpEXT;

extern PFN_vkCmdSetDepthBoundsTestEnableEXT vkCmdSetDepthBoundsTestEnableEXT;

extern PFN_vkCmdSetStencilTestEnableEXT vkCmdSetStencilTestEnableEXT;

extern PFN_vkCmdSetStencilOpEXT vkCmdSetStencilOpEXT;

extern PFN_vkCopyMemoryToImageEXT vkCopyMemoryToImageEXT;

extern PFN_vkCopyImageToMemoryEXT vkCopyImageToMemoryEXT;

extern PFN_vkCopyImageToImageEXT vkCopyImageToImageEXT;

extern PFN_vkTransitionImageLayoutEXT vkTransitionImageLayoutEXT;

extern PFN_vkGetImageSubresourceLayout2EXT vkGetImageSubresourceLayout2EXT;

extern PFN_vkReleaseSwapchainImagesEXT vkReleaseSwapchainImagesEXT;

extern PFN_vkGetGeneratedCommandsMemoryRequirementsNV vkGetGeneratedCommandsMemoryRequirementsNV;

extern PFN_vkCmdPreprocessGeneratedCommandsNV vkCmdPreprocessGeneratedCommandsNV;

extern PFN_vkCmdExecuteGeneratedCommandsNV vkCmdExecuteGeneratedCommandsNV;

extern PFN_vkCmdBindPipelineShaderGroupNV vkCmdBindPipelineShaderGroupNV;

extern PFN_vkCreateIndirectCommandsLayoutNV vkCreateIndirectCommandsLayoutNV;

extern PFN_vkDestroyIndirectCommandsLayoutNV vkDestroyIndirectCommandsLayoutNV;

extern PFN_vkCmdSetDepthBias2EXT vkCmdSetDepthBias2EXT;

extern PFN_vkAcquireDrmDisplayEXT vkAcquireDrmDisplayEXT;

extern PFN_vkGetDrmDisplayEXT vkGetDrmDisplayEXT;

extern PFN_vkCreatePrivateDataSlotEXT vkCreatePrivateDataSlotEXT;

extern PFN_vkDestroyPrivateDataSlotEXT vkDestroyPrivateDataSlotEXT;

extern PFN_vkSetPrivateDataEXT vkSetPrivateDataEXT;

extern PFN_vkGetPrivateDataEXT vkGetPrivateDataEXT;

extern PFN_vkCmdDispatchTileQCOM vkCmdDispatchTileQCOM;

extern PFN_vkCmdBeginPerTileExecutionQCOM vkCmdBeginPerTileExecutionQCOM;

extern PFN_vkCmdEndPerTileExecutionQCOM vkCmdEndPerTileExecutionQCOM;

extern PFN_vkGetDescriptorSetLayoutSizeEXT vkGetDescriptorSetLayoutSizeEXT;

extern PFN_vkGetDescriptorSetLayoutBindingOffsetEXT vkGetDescriptorSetLayoutBindingOffsetEXT;

extern PFN_vkGetDescriptorEXT vkGetDescriptorEXT;

extern PFN_vkCmdBindDescriptorBuffersEXT vkCmdBindDescriptorBuffersEXT;

extern PFN_vkCmdSetDescriptorBufferOffsetsEXT vkCmdSetDescriptorBufferOffsetsEXT;

extern PFN_vkCmdBindDescriptorBufferEmbeddedSamplersEXT vkCmdBindDescriptorBufferEmbeddedSamplersEXT;

extern PFN_vkGetBufferOpaqueCaptureDescriptorDataEXT vkGetBufferOpaqueCaptureDescriptorDataEXT;

extern PFN_vkGetImageOpaqueCaptureDescriptorDataEXT vkGetImageOpaqueCaptureDescriptorDataEXT;

extern PFN_vkGetImageViewOpaqueCaptureDescriptorDataEXT vkGetImageViewOpaqueCaptureDescriptorDataEXT;

extern PFN_vkGetSamplerOpaqueCaptureDescriptorDataEXT vkGetSamplerOpaqueCaptureDescriptorDataEXT;

extern PFN_vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT;

extern PFN_vkCmdSetFragmentShadingRateEnumNV vkCmdSetFragmentShadingRateEnumNV;

extern PFN_vkGetDeviceFaultInfoEXT vkGetDeviceFaultInfoEXT;

extern PFN_vkCmdSetVertexInputEXT vkCmdSetVertexInputEXT;

extern PFN_vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI;

extern PFN_vkCmdSubpassShadingHUAWEI vkCmdSubpassShadingHUAWEI;

extern PFN_vkCmdBindInvocationMaskHUAWEI vkCmdBindInvocationMaskHUAWEI;

extern PFN_vkGetMemoryRemoteAddressNV vkGetMemoryRemoteAddressNV;

extern PFN_vkGetPipelinePropertiesEXT vkGetPipelinePropertiesEXT;

extern PFN_vkCmdSetPatchControlPointsEXT vkCmdSetPatchControlPointsEXT;

extern PFN_vkCmdSetRasterizerDiscardEnableEXT vkCmdSetRasterizerDiscardEnableEXT;

extern PFN_vkCmdSetDepthBiasEnableEXT vkCmdSetDepthBiasEnableEXT;

extern PFN_vkCmdSetLogicOpEXT vkCmdSetLogicOpEXT;

extern PFN_vkCmdSetPrimitiveRestartEnableEXT vkCmdSetPrimitiveRestartEnableEXT;

extern PFN_vkCmdSetColorWriteEnableEXT vkCmdSetColorWriteEnableEXT;

extern PFN_vkCmdDrawMultiEXT vkCmdDrawMultiEXT;

extern PFN_vkCmdDrawMultiIndexedEXT vkCmdDrawMultiIndexedEXT;

extern PFN_vkCreateMicromapEXT vkCreateMicromapEXT;

extern PFN_vkDestroyMicromapEXT vkDestroyMicromapEXT;

extern PFN_vkCmdBuildMicromapsEXT vkCmdBuildMicromapsEXT;

extern PFN_vkBuildMicromapsEXT vkBuildMicromapsEXT;

extern PFN_vkCopyMicromapEXT vkCopyMicromapEXT;

extern PFN_vkCopyMicromapToMemoryEXT vkCopyMicromapToMemoryEXT;

extern PFN_vkCopyMemoryToMicromapEXT vkCopyMemoryToMicromapEXT;

extern PFN_vkWriteMicromapsPropertiesEXT vkWriteMicromapsPropertiesEXT;

extern PFN_vkCmdCopyMicromapEXT vkCmdCopyMicromapEXT;

extern PFN_vkCmdCopyMicromapToMemoryEXT vkCmdCopyMicromapToMemoryEXT;

extern PFN_vkCmdCopyMemoryToMicromapEXT vkCmdCopyMemoryToMicromapEXT;

extern PFN_vkCmdWriteMicromapsPropertiesEXT vkCmdWriteMicromapsPropertiesEXT;

extern PFN_vkGetDeviceMicromapCompatibilityEXT vkGetDeviceMicromapCompatibilityEXT;

extern PFN_vkGetMicromapBuildSizesEXT vkGetMicromapBuildSizesEXT;

extern PFN_vkCmdDrawClusterHUAWEI vkCmdDrawClusterHUAWEI;

extern PFN_vkCmdDrawClusterIndirectHUAWEI vkCmdDrawClusterIndirectHUAWEI;

extern PFN_vkSetDeviceMemoryPriorityEXT vkSetDeviceMemoryPriorityEXT;

extern PFN_vkGetDescriptorSetLayoutHostMappingInfoVALVE vkGetDescriptorSetLayoutHostMappingInfoVALVE;

extern PFN_vkGetDescriptorSetHostMappingVALVE vkGetDescriptorSetHostMappingVALVE;

extern PFN_vkCmdCopyMemoryIndirectNV vkCmdCopyMemoryIndirectNV;

extern PFN_vkCmdCopyMemoryToImageIndirectNV vkCmdCopyMemoryToImageIndirectNV;

extern PFN_vkCmdDecompressMemoryNV vkCmdDecompressMemoryNV;

extern PFN_vkCmdDecompressMemoryIndirectCountNV vkCmdDecompressMemoryIndirectCountNV;

extern PFN_vkGetPipelineIndirectMemoryRequirementsNV vkGetPipelineIndirectMemoryRequirementsNV;

extern PFN_vkCmdUpdatePipelineIndirectBufferNV vkCmdUpdatePipelineIndirectBufferNV;

extern PFN_vkGetPipelineIndirectDeviceAddressNV vkGetPipelineIndirectDeviceAddressNV;

extern PFN_vkGetNativeBufferPropertiesOHOS vkGetNativeBufferPropertiesOHOS;

extern PFN_vkGetMemoryNativeBufferOHOS vkGetMemoryNativeBufferOHOS;

extern PFN_vkCmdSetDepthClampEnableEXT vkCmdSetDepthClampEnableEXT;

extern PFN_vkCmdSetPolygonModeEXT vkCmdSetPolygonModeEXT;

extern PFN_vkCmdSetRasterizationSamplesEXT vkCmdSetRasterizationSamplesEXT;

extern PFN_vkCmdSetSampleMaskEXT vkCmdSetSampleMaskEXT;

extern PFN_vkCmdSetAlphaToCoverageEnableEXT vkCmdSetAlphaToCoverageEnableEXT;

extern PFN_vkCmdSetAlphaToOneEnableEXT vkCmdSetAlphaToOneEnableEXT;

extern PFN_vkCmdSetLogicOpEnableEXT vkCmdSetLogicOpEnableEXT;

extern PFN_vkCmdSetColorBlendEnableEXT vkCmdSetColorBlendEnableEXT;

extern PFN_vkCmdSetColorBlendEquationEXT vkCmdSetColorBlendEquationEXT;

extern PFN_vkCmdSetColorWriteMaskEXT vkCmdSetColorWriteMaskEXT;

extern PFN_vkCmdSetTessellationDomainOriginEXT vkCmdSetTessellationDomainOriginEXT;

extern PFN_vkCmdSetRasterizationStreamEXT vkCmdSetRasterizationStreamEXT;

extern PFN_vkCmdSetConservativeRasterizationModeEXT vkCmdSetConservativeRasterizationModeEXT;

extern PFN_vkCmdSetExtraPrimitiveOverestimationSizeEXT vkCmdSetExtraPrimitiveOverestimationSizeEXT;

extern PFN_vkCmdSetDepthClipEnableEXT vkCmdSetDepthClipEnableEXT;

extern PFN_vkCmdSetSampleLocationsEnableEXT vkCmdSetSampleLocationsEnableEXT;

extern PFN_vkCmdSetColorBlendAdvancedEXT vkCmdSetColorBlendAdvancedEXT;

extern PFN_vkCmdSetProvokingVertexModeEXT vkCmdSetProvokingVertexModeEXT;

extern PFN_vkCmdSetLineRasterizationModeEXT vkCmdSetLineRasterizationModeEXT;

extern PFN_vkCmdSetLineStippleEnableEXT vkCmdSetLineStippleEnableEXT;

extern PFN_vkCmdSetDepthClipNegativeOneToOneEXT vkCmdSetDepthClipNegativeOneToOneEXT;

extern PFN_vkCmdSetViewportWScalingEnableNV vkCmdSetViewportWScalingEnableNV;

extern PFN_vkCmdSetViewportSwizzleNV vkCmdSetViewportSwizzleNV;

extern PFN_vkCmdSetCoverageToColorEnableNV vkCmdSetCoverageToColorEnableNV;

extern PFN_vkCmdSetCoverageToColorLocationNV vkCmdSetCoverageToColorLocationNV;

extern PFN_vkCmdSetCoverageModulationModeNV vkCmdSetCoverageModulationModeNV;

extern PFN_vkCmdSetCoverageModulationTableEnableNV vkCmdSetCoverageModulationTableEnableNV;

extern PFN_vkCmdSetCoverageModulationTableNV vkCmdSetCoverageModulationTableNV;

extern PFN_vkCmdSetShadingRateImageEnableNV vkCmdSetShadingRateImageEnableNV;

extern PFN_vkCmdSetRepresentativeFragmentTestEnableNV vkCmdSetRepresentativeFragmentTestEnableNV;

extern PFN_vkCmdSetCoverageReductionModeNV vkCmdSetCoverageReductionModeNV;

extern PFN_vkCreateTensorARM vkCreateTensorARM;

extern PFN_vkDestroyTensorARM vkDestroyTensorARM;

extern PFN_vkCreateTensorViewARM vkCreateTensorViewARM;

extern PFN_vkDestroyTensorViewARM vkDestroyTensorViewARM;

extern PFN_vkGetTensorMemoryRequirementsARM vkGetTensorMemoryRequirementsARM;

extern PFN_vkBindTensorMemoryARM vkBindTensorMemoryARM;

extern PFN_vkGetDeviceTensorMemoryRequirementsARM vkGetDeviceTensorMemoryRequirementsARM;

extern PFN_vkCmdCopyTensorARM vkCmdCopyTensorARM;

extern PFN_vkGetPhysicalDeviceExternalTensorPropertiesARM vkGetPhysicalDeviceExternalTensorPropertiesARM;

extern PFN_vkGetTensorOpaqueCaptureDescriptorDataARM vkGetTensorOpaqueCaptureDescriptorDataARM;

extern PFN_vkGetTensorViewOpaqueCaptureDescriptorDataARM vkGetTensorViewOpaqueCaptureDescriptorDataARM;

extern PFN_vkGetShaderModuleIdentifierEXT vkGetShaderModuleIdentifierEXT;

extern PFN_vkGetShaderModuleCreateInfoIdentifierEXT vkGetShaderModuleCreateInfoIdentifierEXT;

extern PFN_vkGetPhysicalDeviceOpticalFlowImageFormatsNV vkGetPhysicalDeviceOpticalFlowImageFormatsNV;

extern PFN_vkCreateOpticalFlowSessionNV vkCreateOpticalFlowSessionNV;

extern PFN_vkDestroyOpticalFlowSessionNV vkDestroyOpticalFlowSessionNV;

extern PFN_vkBindOpticalFlowSessionImageNV vkBindOpticalFlowSessionImageNV;

extern PFN_vkCmdOpticalFlowExecuteNV vkCmdOpticalFlowExecuteNV;

extern PFN_vkAntiLagUpdateAMD vkAntiLagUpdateAMD;

extern PFN_vkCreateShadersEXT vkCreateShadersEXT;

extern PFN_vkDestroyShaderEXT vkDestroyShaderEXT;

extern PFN_vkGetShaderBinaryDataEXT vkGetShaderBinaryDataEXT;

extern PFN_vkCmdBindShadersEXT vkCmdBindShadersEXT;

extern PFN_vkCmdSetDepthClampRangeEXT vkCmdSetDepthClampRangeEXT;

extern PFN_vkGetFramebufferTilePropertiesQCOM vkGetFramebufferTilePropertiesQCOM;

extern PFN_vkGetDynamicRenderingTilePropertiesQCOM vkGetDynamicRenderingTilePropertiesQCOM;

extern PFN_vkGetPhysicalDeviceCooperativeVectorPropertiesNV vkGetPhysicalDeviceCooperativeVectorPropertiesNV;

extern PFN_vkConvertCooperativeVectorMatrixNV vkConvertCooperativeVectorMatrixNV;

extern PFN_vkCmdConvertCooperativeVectorMatrixNV vkCmdConvertCooperativeVectorMatrixNV;

extern PFN_vkSetLatencySleepModeNV vkSetLatencySleepModeNV;

extern PFN_vkLatencySleepNV vkLatencySleepNV;

extern PFN_vkSetLatencyMarkerNV vkSetLatencyMarkerNV;

extern PFN_vkGetLatencyTimingsNV vkGetLatencyTimingsNV;

extern PFN_vkQueueNotifyOutOfBandNV vkQueueNotifyOutOfBandNV;

extern PFN_vkCreateDataGraphPipelinesARM vkCreateDataGraphPipelinesARM;

extern PFN_vkCreateDataGraphPipelineSessionARM vkCreateDataGraphPipelineSessionARM;

extern PFN_vkGetDataGraphPipelineSessionBindPointRequirementsARM vkGetDataGraphPipelineSessionBindPointRequirementsARM;

extern PFN_vkGetDataGraphPipelineSessionMemoryRequirementsARM vkGetDataGraphPipelineSessionMemoryRequirementsARM;

extern PFN_vkBindDataGraphPipelineSessionMemoryARM vkBindDataGraphPipelineSessionMemoryARM;

extern PFN_vkDestroyDataGraphPipelineSessionARM vkDestroyDataGraphPipelineSessionARM;

extern PFN_vkCmdDispatchDataGraphARM vkCmdDispatchDataGraphARM;

extern PFN_vkGetDataGraphPipelineAvailablePropertiesARM vkGetDataGraphPipelineAvailablePropertiesARM;

extern PFN_vkGetDataGraphPipelinePropertiesARM vkGetDataGraphPipelinePropertiesARM;

extern PFN_vkGetPhysicalDeviceQueueFamilyDataGraphPropertiesARM vkGetPhysicalDeviceQueueFamilyDataGraphPropertiesARM;

extern PFN_vkGetPhysicalDeviceQueueFamilyDataGraphProcessingEnginePropertiesARM vkGetPhysicalDeviceQueueFamilyDataGraphProcessingEnginePropertiesARM;

extern PFN_vkCmdSetAttachmentFeedbackLoopEnableEXT vkCmdSetAttachmentFeedbackLoopEnableEXT;

extern PFN_vkCmdBindTileMemoryQCOM vkCmdBindTileMemoryQCOM;

extern PFN_vkCmdDecompressMemoryEXT vkCmdDecompressMemoryEXT;

extern PFN_vkCmdDecompressMemoryIndirectCountEXT vkCmdDecompressMemoryIndirectCountEXT;

extern PFN_vkCreateExternalComputeQueueNV vkCreateExternalComputeQueueNV;

extern PFN_vkDestroyExternalComputeQueueNV vkDestroyExternalComputeQueueNV;

extern PFN_vkGetExternalComputeQueueDataNV vkGetExternalComputeQueueDataNV;

extern PFN_vkGetClusterAccelerationStructureBuildSizesNV vkGetClusterAccelerationStructureBuildSizesNV;

extern PFN_vkCmdBuildClusterAccelerationStructureIndirectNV vkCmdBuildClusterAccelerationStructureIndirectNV;

extern PFN_vkGetPartitionedAccelerationStructuresBuildSizesNV vkGetPartitionedAccelerationStructuresBuildSizesNV;

extern PFN_vkCmdBuildPartitionedAccelerationStructuresNV vkCmdBuildPartitionedAccelerationStructuresNV;

extern PFN_vkGetGeneratedCommandsMemoryRequirementsEXT vkGetGeneratedCommandsMemoryRequirementsEXT;

extern PFN_vkCmdPreprocessGeneratedCommandsEXT vkCmdPreprocessGeneratedCommandsEXT;

extern PFN_vkCmdExecuteGeneratedCommandsEXT vkCmdExecuteGeneratedCommandsEXT;

extern PFN_vkCreateIndirectCommandsLayoutEXT vkCreateIndirectCommandsLayoutEXT;

extern PFN_vkDestroyIndirectCommandsLayoutEXT vkDestroyIndirectCommandsLayoutEXT;

extern PFN_vkCreateIndirectExecutionSetEXT vkCreateIndirectExecutionSetEXT;

extern PFN_vkDestroyIndirectExecutionSetEXT vkDestroyIndirectExecutionSetEXT;

extern PFN_vkUpdateIndirectExecutionSetPipelineEXT vkUpdateIndirectExecutionSetPipelineEXT;

extern PFN_vkUpdateIndirectExecutionSetShaderEXT vkUpdateIndirectExecutionSetShaderEXT;

extern PFN_vkGetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV vkGetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV;

extern PFN_vkEnumeratePhysicalDeviceQueueFamilyPerformanceCountersByRegionARM vkEnumeratePhysicalDeviceQueueFamilyPerformanceCountersByRegionARM;

extern PFN_vkCmdEndRendering2EXT vkCmdEndRendering2EXT;

extern PFN_vkCmdBeginCustomResolveEXT vkCmdBeginCustomResolveEXT;

extern PFN_vkCmdSetComputeOccupancyPriorityNV vkCmdSetComputeOccupancyPriorityNV;

extern PFN_vkCreateUbmSurfaceSEC vkCreateUbmSurfaceSEC;

extern PFN_vkGetPhysicalDeviceUbmPresentationSupportSEC vkGetPhysicalDeviceUbmPresentationSupportSEC;

extern PFN_vkCreateAccelerationStructureKHR vkCreateAccelerationStructureKHR;

extern PFN_vkDestroyAccelerationStructureKHR vkDestroyAccelerationStructureKHR;

extern PFN_vkCmdBuildAccelerationStructuresKHR vkCmdBuildAccelerationStructuresKHR;

extern PFN_vkCmdBuildAccelerationStructuresIndirectKHR vkCmdBuildAccelerationStructuresIndirectKHR;

extern PFN_vkBuildAccelerationStructuresKHR vkBuildAccelerationStructuresKHR;

extern PFN_vkCopyAccelerationStructureKHR vkCopyAccelerationStructureKHR;

extern PFN_vkCopyAccelerationStructureToMemoryKHR vkCopyAccelerationStructureToMemoryKHR;

extern PFN_vkCopyMemoryToAccelerationStructureKHR vkCopyMemoryToAccelerationStructureKHR;

extern PFN_vkWriteAccelerationStructuresPropertiesKHR vkWriteAccelerationStructuresPropertiesKHR;

extern PFN_vkCmdCopyAccelerationStructureKHR vkCmdCopyAccelerationStructureKHR;

extern PFN_vkCmdCopyAccelerationStructureToMemoryKHR vkCmdCopyAccelerationStructureToMemoryKHR;

extern PFN_vkCmdCopyMemoryToAccelerationStructureKHR vkCmdCopyMemoryToAccelerationStructureKHR;

extern PFN_vkGetAccelerationStructureDeviceAddressKHR vkGetAccelerationStructureDeviceAddressKHR;

extern PFN_vkCmdWriteAccelerationStructuresPropertiesKHR vkCmdWriteAccelerationStructuresPropertiesKHR;

extern PFN_vkGetDeviceAccelerationStructureCompatibilityKHR vkGetDeviceAccelerationStructureCompatibilityKHR;

extern PFN_vkGetAccelerationStructureBuildSizesKHR vkGetAccelerationStructureBuildSizesKHR;

extern PFN_vkCmdTraceRaysKHR vkCmdTraceRaysKHR;

extern PFN_vkCreateRayTracingPipelinesKHR vkCreateRayTracingPipelinesKHR;

extern PFN_vkGetRayTracingCaptureReplayShaderGroupHandlesKHR vkGetRayTracingCaptureReplayShaderGroupHandlesKHR;

extern PFN_vkCmdTraceRaysIndirectKHR vkCmdTraceRaysIndirectKHR;

extern PFN_vkGetRayTracingShaderGroupStackSizeKHR vkGetRayTracingShaderGroupStackSizeKHR;

extern PFN_vkCmdSetRayTracingPipelineStackSizeKHR vkCmdSetRayTracingPipelineStackSizeKHR;

extern PFN_vkCmdDrawMeshTasksEXT vkCmdDrawMeshTasksEXT;

extern PFN_vkCmdDrawMeshTasksIndirectEXT vkCmdDrawMeshTasksIndirectEXT;

extern PFN_vkCmdDrawMeshTasksIndirectCountEXT vkCmdDrawMeshTasksIndirectCountEXT;

#if defined( VK_ENABLE_BETA_EXTENSIONS )
	extern PFN_vkCreateExecutionGraphPipelinesAMDX vkCreateExecutionGraphPipelinesAMDX;

extern PFN_vkGetExecutionGraphPipelineScratchSizeAMDX vkGetExecutionGraphPipelineScratchSizeAMDX;

extern PFN_vkGetExecutionGraphPipelineNodeIndexAMDX vkGetExecutionGraphPipelineNodeIndexAMDX;

extern PFN_vkCmdInitializeGraphScratchMemoryAMDX vkCmdInitializeGraphScratchMemoryAMDX;

extern PFN_vkCmdDispatchGraphAMDX vkCmdDispatchGraphAMDX;

extern PFN_vkCmdDispatchGraphIndirectAMDX vkCmdDispatchGraphIndirectAMDX;

extern PFN_vkCmdDispatchGraphIndirectCountAMDX vkCmdDispatchGraphIndirectCountAMDX;

extern PFN_vkCreateCudaModuleNV vkCreateCudaModuleNV;

extern PFN_vkGetCudaModuleCacheNV vkGetCudaModuleCacheNV;

extern PFN_vkCreateCudaFunctionNV vkCreateCudaFunctionNV;

extern PFN_vkDestroyCudaModuleNV vkDestroyCudaModuleNV;

extern PFN_vkDestroyCudaFunctionNV vkDestroyCudaFunctionNV;

extern PFN_vkCmdCudaLaunchKernelNV vkCmdCudaLaunchKernelNV;

#endif

#if defined( VK_USE_PLATFORM_WIN32_KHR )
	extern PFN_vkCreateWin32SurfaceKHR vkCreateWin32SurfaceKHR;

extern PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR vkGetPhysicalDeviceWin32PresentationSupportKHR;

extern PFN_vkGetMemoryWin32HandleKHR vkGetMemoryWin32HandleKHR;

extern PFN_vkGetMemoryWin32HandlePropertiesKHR vkGetMemoryWin32HandlePropertiesKHR;

extern PFN_vkImportSemaphoreWin32HandleKHR vkImportSemaphoreWin32HandleKHR;

extern PFN_vkGetSemaphoreWin32HandleKHR vkGetSemaphoreWin32HandleKHR;

extern PFN_vkImportFenceWin32HandleKHR vkImportFenceWin32HandleKHR;

extern PFN_vkGetFenceWin32HandleKHR vkGetFenceWin32HandleKHR;

extern PFN_vkGetMemoryWin32HandleNV vkGetMemoryWin32HandleNV;

extern PFN_vkGetPhysicalDeviceSurfacePresentModes2EXT vkGetPhysicalDeviceSurfacePresentModes2EXT;

extern PFN_vkAcquireFullScreenExclusiveModeEXT vkAcquireFullScreenExclusiveModeEXT;

extern PFN_vkReleaseFullScreenExclusiveModeEXT vkReleaseFullScreenExclusiveModeEXT;

extern PFN_vkGetDeviceGroupSurfacePresentModes2EXT vkGetDeviceGroupSurfacePresentModes2EXT;

extern PFN_vkAcquireWinrtDisplayNV vkAcquireWinrtDisplayNV;

extern PFN_vkGetWinrtDisplayNV vkGetWinrtDisplayNV;

#endif

#if defined( VK_USE_PLATFORM_WAYLAND_KHR )
	extern PFN_vkCreateWaylandSurfaceKHR vkCreateWaylandSurfaceKHR;

extern PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR vkGetPhysicalDeviceWaylandPresentationSupportKHR;

#endif

#if defined( VK_USE_PLATFORM_XLIB_KHR )
	extern PFN_vkCreateXlibSurfaceKHR vkCreateXlibSurfaceKHR;

extern PFN_vkGetPhysicalDeviceXlibPresentationSupportKHR vkGetPhysicalDeviceXlibPresentationSupportKHR;

#endif

#if defined( VK_USE_PLATFORM_XLIB_XRANDR_EXT )
	extern PFN_vkAcquireXlibDisplayEXT vkAcquireXlibDisplayEXT;

extern PFN_vkGetRandROutputDisplayEXT vkGetRandROutputDisplayEXT;

#endif

#endif // VULKAN_LOADER_H