set(DAEMON_BUILDINFO_HEADER "// Automatically generated, do not modify!\n")
set(DAEMON_BUILDINFO_PARENT "${CMAKE_CURRENT_BINARY_DIR}/GeneratedSource")
set(DAEMON_BUILDINFO_DIR "DaemonBuildInfo")
set(DAEMON_BUILDINFO_DIR_FULLPATH "${DAEMON_BUILDINFO_PARENT}/${DAEMON_BUILDINFO_DIR}")
set(DAEMON_BUILDINFO_CPP_EXT ".cpp")
set(DAEMON_BUILDINFO_H_EXT ".h")
set(BUILDINFOLIST)

file(MAKE_DIRECTORY "${DAEMON_BUILDINFO_DIR_FULLPATH}")
include_directories("${DAEMON_BUILDINFO_PARENT}")

foreach(kind CPP H)
	set(DAEMON_BUILDINFO_${kind} "${DAEMON_BUILDINFO_HEADER}")
endforeach()

macro(daemon_add_buildinfo TYPE NAME VALUE)
	set(DAEMON_BUILDINFO_CPP "${DAEMON_BUILDINFO_CPP}const ${TYPE} ${NAME}=${VALUE};\n")
	set(DAEMON_BUILDINFO_H "${DAEMON_BUILDINFO_H}extern const ${TYPE} ${NAME};\n")
endmacro()

macro(daemon_write_generated GENERATED_SLUG GENERATED_PATH GENERATED_CONTENT)
	set(DAEMON_GENERATED_FILE ${DAEMON_BUILDINFO_PARENT}/${GENERATED_PATH})

	if (EXISTS "${DAEMON_GENERATED_FILE}")
		file(READ "${DAEMON_GENERATED_FILE}" GENERATED_CONTENT_READ)
	endif()

	if (NOT "${GENERATED_CONTENT}" STREQUAL "${GENERATED_CONTENT_READ}")
		message(STATUS "Generating ${GENERATED_PATH}")
		file(WRITE "${DAEMON_GENERATED_FILE}" "${GENERATED_CONTENT}")
	endif()
endmacro()

macro(daemon_write_buildinfo NAME)
	foreach(kind CPP H)
		set(BUILDINFO_SLUG "BUILDINFO_${kind}")
		set(DAEMON_${BUILDINFO_SLUG}_NAME "${NAME}${DAEMON_${BUILDINFO_SLUG}_EXT}")
		set(DAEMON_${BUILDINFO_SLUG}_PATH "${DAEMON_BUILDINFO_DIR}/${DAEMON_${BUILDINFO_SLUG}_NAME}")

		daemon_write_generated("${BUILDINFO_SLUG}" "${DAEMON_${BUILDINFO_SLUG}_PATH}" "${DAEMON_${BUILDINFO_SLUG}}")
		list(APPEND BUILDINFOLIST "${DAEMON_GENERATED_FILE}")
	endforeach()
endmacro()
